name: Automated Preprocessing

on:
  push:
    branches:
      - main   # Trigger setiap push ke main branch
  workflow_dispatch:  # Bisa dijalankan manual

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run preprocessing
      run: |
        python Preprocessing/automate_AzrielKevin.py \
          --input_path Dataset/Metro_Interstate_Traffic_Volume.csv \
          --output_csv Preprocessing/Metro_Interstate_Traffic_Volume_preprocessing.csv \
          --pipeline_path Preprocessing/Metro_Interstate_Traffic_Volume_preprocessing/preprocessor_pipeline.joblib \
          --header_path Preprocessing/Metro_Interstate_Traffic_Volume_preprocessing/feature_header.csv \
          --target_column traffic_volume

    - name: Commit & push processed dataset
      run: |
        git config --global user.name "azrielkevinalfarizqi"
        git config --global user.email "kevinazriel28@gmail.com"
        git add Preprocessing/Metro_Interstate_Traffic_Volume_preprocessing.csv
        git commit -m "Update preprocessing dataset (auto)" || echo "No changes to commit"
        git push
